<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_We texted your phone XX XXXXXXXX42. P_5eea8e</name>
   <tag></tag>
   <elementGuidId>4c67537f-2a53-42b5-bdb8-9f5bc61f3121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idTxtBx_SAOTCC_OTC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idTxtBx_SAOTCC_OTC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0ea3ec5-4679-4ef2-893b-b7986237f5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idTxtBx_SAOTCC_OTC</value>
      <webElementGuid>31f17217-761c-4b25-b706-2148cbb4e0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otc</value>
      <webElementGuid>3f69a5f0-c0a9-45a8-941b-b5684bc08a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3a5f193e-f380-4a8c-9671-eb744b666846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>c666e6e4-8235-400c-8fa1-ed3fe55948e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7e9405b9-c197-47aa-95f2-6cdd3330eca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6fa58351-9507-4dc9-b77b-49260ff45c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                    attr: { 'maxlength': otcLength, 'aria-labelledby': 'idTxtBx_SAOTCC_OTC idDiv_SAOTCC_Title idDiv_SAOTCC_Description', 'aria-describedby':'idSpan_SAOTCC_Error_OTC' },
                    css: { 'has-error': error },
                    textInput: otcInputTextbox.value,
                    ariaLabel: str['CT_SAOTCC_STR_OTC_TBHint'],
                    hasFocusEx: otcInputTextbox.focused,
                    placeholder: $placeholderText</value>
      <webElementGuid>e8aa6862-9e23-41fd-b6d1-64a410fc8a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>643ac406-f3c7-4b67-8d8a-2734db9e3459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>idTxtBx_SAOTCC_OTC idDiv_SAOTCC_Title idDiv_SAOTCC_Description</value>
      <webElementGuid>43cbccce-0225-494c-aee1-d331d46227a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>idSpan_SAOTCC_Error_OTC</value>
      <webElementGuid>c1322489-a92a-44d5-8742-80972cdfe2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>2616d03d-c3c3-4cbd-a8ab-17a4394f9cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>9668a95e-c51f-4c54-be0f-085141183c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTxtBx_SAOTCC_OTC&quot;)</value>
      <webElementGuid>6b3f0cff-a1cc-4d9a-a531-142fb223a49a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idTxtBx_SAOTCC_OTC']</value>
      <webElementGuid>f14733c0-6fd9-4b0d-9609-9f2ba38e79f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idDiv_SAOTCC_OTC']/div/input</value>
      <webElementGuid>8028551d-b846-45f9-a99f-6da23edc26e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>a0f1a551-b729-4227-8911-6d3af7b607cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idTxtBx_SAOTCC_OTC' and @name = 'otc' and @type = 'tel' and @placeholder = 'Code']</value>
      <webElementGuid>603c0797-ab85-4757-9082-9a9e2999d72f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
