<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Date_date-picker-inline</name>
   <tag></tag>
   <elementGuidId>964b7bba-0025-43a8-8da4-71c9cb00f59d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root-754.MuiOutlinedInput-root-742.Mui-focused.Mui-focused.MuiInputBase-formControl-755.MuiInputBase-adornedEnd-757.MuiOutlinedInput-adornedEnd-745.MuiInputBase-marginDense-758.MuiOutlinedInput-marginDense-746 > #date-picker-inline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='date-picker-inline'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b56b0551-fd02-47d5-bf3c-5140d0df09f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a4fbf7dc-6162-4e45-82bd-4d0932ee4c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date-picker-inline</value>
      <webElementGuid>54bc9312-b0b1-4a70-a09e-9a3cc0669082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>f184767b-c8bc-47a5-9b53-8393642c8abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f537309a-2beb-4423-9701-20f038c15d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-762 MuiOutlinedInput-input-749 MuiInputBase-inputAdornedEnd-767 MuiOutlinedInput-inputAdornedEnd-753 MuiInputBase-inputMarginDense-763 MuiOutlinedInput-inputMarginDense-750</value>
      <webElementGuid>3088acfd-9fe6-422e-abef-e20a6c900904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>55/55/5555</value>
      <webElementGuid>23c5e0c1-d3cc-4d0b-810e-7d1a04b0a0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>date-picker-inline-helper-text</value>
      <webElementGuid>b434a24b-c305-473c-b4e4-1e5cf93b7a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fznxKY kfRyXm body&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;MuiContainer-root h-100&quot;]/div[@class=&quot;sc-pjSSY dAvxTh&quot;]/div[@class=&quot;MuiPaper-root MuiCard-root sc-qQmou jqDvEh MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;sc-qYiqT gQdAZa&quot;]/div[@class=&quot;sc-pAZqv cuOtHq&quot;]/div[@class=&quot;sc-pRTZB cgrjKw&quot;]/div[@class=&quot;sc-pJurq cTjcEC&quot;]/div[@class=&quot;sc-paXsP fwwEgA&quot;]/div[@class=&quot;MuiFormControl-root-726 MuiTextField-root-725 jss95&quot;]/div[@class=&quot;MuiInputBase-root-754 MuiOutlinedInput-root-742 Mui-focused Mui-focused MuiInputBase-formControl-755 MuiInputBase-adornedEnd-757 MuiOutlinedInput-adornedEnd-745 MuiInputBase-marginDense-758 MuiOutlinedInput-marginDense-746&quot;]/input[@id=&quot;date-picker-inline&quot;]</value>
      <webElementGuid>2c811497-a0c3-4f93-9523-43802631c7c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='date-picker-inline'])[2]</value>
      <webElementGuid>ddcad741-4625-4780-84e0-06d7b89b584c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div/div[4]/div[3]/div[3]/div/div/input</value>
      <webElementGuid>9bf5b8fe-0a74-4bc4-8560-372ede8d8cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/input</value>
      <webElementGuid>6dd502e3-09b7-477a-b986-0220e39d0aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'date-picker-inline' and @placeholder = 'DD/MM/YYYY' and @type = 'text']</value>
      <webElementGuid>073b1daa-2641-4a01-ac4d-996c8ff53c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
