<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Date_date-picker-inline</name>
   <tag></tag>
   <elementGuidId>6eaf0589-593a-4478-b90c-7dda5a1902d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#date-picker-inline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='date-picker-inline']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>894fefb3-03d4-4026-9bfc-6ac96f5e6eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c33e6281-cdb6-4b6b-9773-f39cc1935313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date-picker-inline</value>
      <webElementGuid>4e5c324b-02f3-46a5-8fe9-0d52ed1de558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>8c70d286-5950-40f6-a2b3-1c5893830d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b001e525-6bc8-4549-999d-1d212808ca3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-687 MuiOutlinedInput-input-674 MuiInputBase-inputAdornedEnd-692 MuiOutlinedInput-inputAdornedEnd-678 MuiInputBase-inputMarginDense-688 MuiOutlinedInput-inputMarginDense-675</value>
      <webElementGuid>e10ee427-b5ad-4848-ba59-3be0fd3d390d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fznxKY kfRyXm body&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;MuiContainer-root h-100&quot;]/div[@class=&quot;sc-pjSSY dAvxTh&quot;]/div[@class=&quot;MuiPaper-root MuiCard-root sc-qQmou jqDvEh MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;sc-qYiqT gQdAZa&quot;]/div[@class=&quot;sc-pAZqv cuOtHq&quot;]/div[@class=&quot;sc-pRTZB cgrjKw&quot;]/div[@class=&quot;sc-pJurq cTjcEC&quot;]/div[@class=&quot;sc-paXsP fwwEgA&quot;]/div[@class=&quot;MuiFormControl-root-651 MuiTextField-root-650 jss95&quot;]/div[@class=&quot;MuiInputBase-root-679 MuiOutlinedInput-root-667 Mui-focused Mui-focused MuiInputBase-formControl-680 MuiInputBase-adornedEnd-682 MuiOutlinedInput-adornedEnd-670 MuiInputBase-marginDense-683 MuiOutlinedInput-marginDense-671&quot;]/input[@id=&quot;date-picker-inline&quot;]</value>
      <webElementGuid>851edc2d-6941-4175-adf6-c820e4b96f12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='date-picker-inline']</value>
      <webElementGuid>c057d286-8bd4-42a9-aadf-094dc56bf5fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div/div[4]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>4ed143f7-ce7b-4bdd-8dd4-67d5cdd15550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>c1616e8d-d6ce-4674-9c2e-6d6b7b447f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'date-picker-inline' and @placeholder = 'DD/MM/YYYY' and @type = 'text']</value>
      <webElementGuid>a748a33c-3e3d-4243-afa7-15db477f02ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
