<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Date_date-picker-inline</name>
   <tag></tag>
   <elementGuidId>2772f779-2728-450f-bfe0-98b585a454c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='date-picker-inline']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#date-picker-inline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef7f8c67-4c3c-43c2-afa4-2271edbd9e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5cf59cbb-9f0c-48d3-9993-b470953f4ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date-picker-inline</value>
      <webElementGuid>eaa59b78-e9d7-4c8d-a4b7-55b6ab3d0df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>0151fe6b-b5fd-419f-a1d3-1b729dd6b224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc3a2b53-6398-40af-96cb-4d9dee91b6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-133 MuiOutlinedInput-input-120 MuiInputBase-inputAdornedEnd-138 MuiOutlinedInput-inputAdornedEnd-124 MuiInputBase-inputMarginDense-134 MuiOutlinedInput-inputMarginDense-121</value>
      <webElementGuid>4c9d2b8c-3351-4e28-b3c1-70c7547cec09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fznxKY kfRyXm body&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;MuiContainer-root h-100&quot;]/div[@class=&quot;sc-pjSSY dAvxTh&quot;]/div[@class=&quot;MuiPaper-root MuiCard-root sc-qQmou jqDvEh MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;sc-qYiqT gQdAZa&quot;]/div[@class=&quot;sc-pAZqv cuOtHq&quot;]/div[@class=&quot;sc-pRTZB cgrjKw&quot;]/div[@class=&quot;sc-pJurq cTjcEC&quot;]/div[@class=&quot;sc-paXsP fwwEgA&quot;]/div[@class=&quot;MuiFormControl-root-97 MuiTextField-root-96 jss95&quot;]/div[@class=&quot;MuiInputBase-root-125 MuiOutlinedInput-root-113 Mui-focused Mui-focused MuiInputBase-formControl-126 MuiInputBase-adornedEnd-128 MuiOutlinedInput-adornedEnd-116 MuiInputBase-marginDense-129 MuiOutlinedInput-marginDense-117&quot;]/input[@id=&quot;date-picker-inline&quot;]</value>
      <webElementGuid>4ae28f06-b0db-4eb5-8c51-a2b997ee4912</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='date-picker-inline']</value>
      <webElementGuid>ccf65f0c-24a1-495a-b281-75e2e352590b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div/div[4]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>052a3997-5920-47b2-903e-bc9a5bd3bdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>243e21de-607d-4657-ac18-962bf516f31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'date-picker-inline' and @placeholder = 'DD/MM/YYYY' and @type = 'text']</value>
      <webElementGuid>7b667f85-44b8-4d23-a0e9-2153117602bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
