<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TestACtivity1</name>
   <tag></tag>
   <elementGuidId>28cb446f-0007-4e0e-bc53-9f226993f6b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-fznXWL.cmbVUc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b7adc5e0-35bc-47f1-8d95-4f3835827da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fznXWL cmbVUc</value>
      <webElementGuid>f3322ccb-734e-4052-8cc3-7e093dd656d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TestACtivity1</value>
      <webElementGuid>bb9d43d5-e976-4738-a413-f303163ee1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fznxKY kfRyXm body&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;MuiContainer-root h-100&quot;]/div[@class=&quot;sc-pRFjI iisorR&quot;]/div[@class=&quot;sc-fznBtT ccaska&quot;]/div[@class=&quot;sc-fznNTe fnbSrb&quot;]/div[@class=&quot;MuiGrid-root h-100 MuiGrid-container MuiGrid-spacing-xs-2&quot;]/div[@class=&quot;MuiGrid-root dis-flex h-100 MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-6&quot;]/div[@class=&quot;MuiPaper-root MuiCard-root sc-fzobTh ktGuED MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;sc-fzonjX skboX&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;sc-fznyYp kdOAmQ&quot;]/div[@class=&quot;sc-fznLxA gQRraV&quot;]/div[@class=&quot;sc-fznXWL cmbVUc&quot;]</value>
      <webElementGuid>99bb1347-f4a0-4776-a9dc-83f9ba79052c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>f947e83e-c0e7-4bed-93e3-8d169cc914cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discussion'])[1]/following::div[5]</value>
      <webElementGuid>3054e5bd-3be9-4aad-b797-a03732737878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self Evaluation'])[1]/following::div[6]</value>
      <webElementGuid>fed7b571-3d52-4d3b-ae64-b26d4ab87111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[1]/preceding::div[2]</value>
      <webElementGuid>9d564ef4-8a59-4233-98b9-43bfb1dbce88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Milestones'])[1]/preceding::div[3]</value>
      <webElementGuid>405d6d46-b879-4cd9-895d-f4ec615b904d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TestACtivity1']/parent::*</value>
      <webElementGuid>9b3de7ad-6616-4343-905f-953445b9833d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>ed485ba6-d967-4188-9700-74c91c22821d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TestACtivity1' or . = 'TestACtivity1')]</value>
      <webElementGuid>2cad0b48-2696-4ea6-a75a-42644cf9c049</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
